name: exercicios_app
description: Um app para lista de exercícios

publish_to: "none" # Descomente para publicar no pub.dev

environment:
  sdk: ">=2.19.0 <3.0.0" # Ou use uma versão mais recente compatível com null safety

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 # Versão atualizada do cupertino_icons
  http: ^1.2.2

flutter:
  uses-material-design: true
